### ISSUE TITLE
Bug: webchat: ConnectionResetError: [WinError 10054] 

### ISSUE THREAD

**Issue by LoveYakamoz** [LoveYakamoz/Quantitative_Trading#4]

**Comment by LoveYakamoz** [comment]
2017-06-11 10:56:45,994 - webchat_robot.py:857 - Robot - generic exception: Traceback (most recent call last):
  File "webchat_robot.py", line 845, in _get
  File "urllib\request.py", line 163, in urlopen
  File "urllib\request.py", line 466, in open
  File "urllib\request.py", line 484, in _open
  File "urllib\request.py", line 444, in _call_chain
  File "urllib\request.py", line 1297, in https_open
  File "urllib\request.py", line 1257, in do_open
  File "http\client.py", line 1197, in getresponse
  File "http\client.py", line 297, in begin
  File "http\client.py", line 258, in _read_status
  File "socket.py", line 575, in readinto
  File "ssl.py", line 929, in recv_into
  File "ssl.py", line 791, in read
  File "ssl.py", line 575, in read
ConnectionResetError: [WinError 10054]

**Comment by LoveYakamoz** [comment]
Python socket.error: [Errno 10054] 远程主机强迫关闭了一个现有的连接。问题解决方案：
前几天使用python读取网页。因为对一个网站大量的使用urlopen操作，所以会被那个网站认定为攻击行为。有时就不再允许下载。导致urlopen()后，request.read()一直卡死在那里。最后会抛出errno 10054.
这个错误是connection reset by peer.也就是传说的远端主机重置了此连接。原因可能是socket超时时间过长；也可能是request = urllib.request.urlopen(url)之后，没有进行request.close()操作；也可能是没有sleep几秒，导致网站认定这种行为是攻击。
